version: '3'
services:
  web:
    build: ./web
    environment:
      - 'APACHE_RUN_USER:www-data'
      - 'APACHE_RUN_GROUP:www-data'
    volumes:
      - '${APP_PATH_HOST}:${APP_PATH_CONTAINER}'
    ports:
      - '8080:80'
    working_dir: '${APP_PATH_CONTAINER}'
  mysql:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qzwxec123
    volumes:
      - '${DB_PATH_HOST}:/var/lib/mysql'
    ports:
      - '3306:3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - '6080:8080'
  composer:
    image: composer
    volumes:
      - '${APP_PATH_HOST}:${APP_PATH_CONTAINER}'
    working_dir: '${APP_PATH_CONTAINER}'
